### ISSUE TITLE
dfu detach not required to start program

### ISSUE THREAD

**Issue by noah95** [im-tomu/foboot#11]
According to the readme a `dfu-util -e` has to be executed after downloading an image to start the new bitstream.

In my experience, running the riscv-blink on a fomu hacker board the program immediately starts execution after dfu download is complete.

Running `Fomu DFU Bootloader v1.7.3-1-g82cb20c` and dfu util v0.8 on Ubuntu.

Can someone explain me where in the bootloader the reset is executed after download?

**Comment by xobs** [comment]
I've updated the `README.md` to give correct information about the usage of `dfu-util -e`.  It used to be a two-step process (due to timing restrictions), but was eventually collapsed into a one-step process.

The actual reboot is handled as part of the `DFU_DETACH` message that is parsed in https://github.com/im-tomu/foboot/blob/master/sw/src/usb-dev.c#L190

**Comment by noah95** [comment]
Thank you very much @xobs  for the explanations
